####
POST http://localhost:3000/register/
Content-Type:application/json

{ 
  "username": "Balaji_2222",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

####
POST http://localhost:3000/login/
Content-Type:application/json

{
    "username":"Balaji_2222",
    "password":"richard_567"
}

####
GET http://localhost:3000/user/following/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhbGFqaV8yMjIyIiwiaWF0IjoxNzAxNjc1MTc1fQ.e924RlTovPNGciCK9xB69M1cVp6wr43T2apzQRzZa_M